package HelloWorldData;


/**
* HelloWorldData/Msg.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/helloworld/src/main/idl/HelloWorldData.idl
* lundi 25 février 2019 12 h 35 CET
*/

/**
* Updated by idl2j
* from /home/ndrianja/IST/jmobile/examples/helloworld/src/main/idl/HelloWorldData.idl
* lundi 25 février 2019 12 h 35 CET
*/

import HelloWorldData.KeyList;

@KeyList(
    topicType = "Msg",
    keys = {"userID"}
)
public final class Msg implements org.omg.CORBA.portable.IDLEntity
{
  public int userID = (int)0;

  // User ID
  public String message = null;

  public Msg ()
  {
  } // ctor

  public Msg (int _userID, String _message)
  {
    userID = _userID;
    message = _message;
  } // ctor

} // class Msg
