package ThroughputModule;

/**
* ThroughputModule/DataTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/throughput/src/main/idl/ThroughputData.idl
* lundi 25 février 2019 12 h 34 CET
*/

public final class DataTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ThroughputModule.DataType value = null;

  public DataTypeHolder ()
  {
  }

  public DataTypeHolder (ThroughputModule.DataType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ThroughputModule.DataTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ThroughputModule.DataTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ThroughputModule.DataTypeHelper.type ();
  }

}
