__LINE__=__LINE__
__FILE__=__FILE__
__COUNTER__=__COUNTER__
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
NDEBUG=NDEBUG => 1
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
STDC_HEADERS=STDC_HEADERS => 1
__GNUC__=__GNUC__ => 1
TARGET_CPU_X86_64=TARGET_CPU_X86_64 => 1
__i386__=__i386__ => 1
__x86_64__=__x86_64__ => 1
__amd64__=__amd64__ => 1
M_I86=M_I86 => 1
_M_I86=_M_I86 => 1
_WIN32=_WIN32 => 1
__attribute__=__attribute__(x)
DDS_H=DDS_H
DDS_IMPL_H=DDS_IMPL_H
DDS_LENGTH_UNLIMITED=DDS_LENGTH_UNLIMITED => -1
DDS_TOPIC_NO_OPTIMIZE=DDS_TOPIC_NO_OPTIMIZE => 0x0001
DDS_TOPIC_FIXED_KEY=DDS_TOPIC_FIXED_KEY => 0x0002
DDS_READ_SAMPLE_STATE=DDS_READ_SAMPLE_STATE => 1u
DDS_NOT_READ_SAMPLE_STATE=DDS_NOT_READ_SAMPLE_STATE => 2u
DDS_ANY_SAMPLE_STATE=DDS_ANY_SAMPLE_STATE => (1u | 2u)
DDS_NEW_VIEW_STATE=DDS_NEW_VIEW_STATE => 4u
DDS_NOT_NEW_VIEW_STATE=DDS_NOT_NEW_VIEW_STATE => 8u
DDS_ANY_VIEW_STATE=DDS_ANY_VIEW_STATE => (4u | 8u)
DDS_ALIVE_INSTANCE_STATE=DDS_ALIVE_INSTANCE_STATE => 16u
DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE=DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE => 32u
DDS_NOT_ALIVE_NO_WRITERS_INSTANCE_STATE=DDS_NOT_ALIVE_NO_WRITERS_INSTANCE_STATE => 64u
DDS_ANY_INSTANCE_STATE=DDS_ANY_INSTANCE_STATE => (16u | 32u | 64u)
DDS_ANY_STATE=DDS_ANY_STATE => (DDS_ANY_SAMPLE_STATE | DDS_ANY_VIEW_STATE | DDS_ANY_INSTANCE_STATE)
DDS_DOMAIN_DEFAULT=DDS_DOMAIN_DEFAULT => -1
DDS_HANDLE_NIL=DDS_HANDLE_NIL => 0
DDS_ENTITY_NIL=DDS_ENTITY_NIL => 0
DDS_ENTITY_KIND_MASK=DDS_ENTITY_KIND_MASK => (0x7F000000)
DDS_OP_RTS=DDS_OP_RTS => 0x00000000
DDS_OP_ADR=DDS_OP_ADR => 0x01000000
DDS_OP_JSR=DDS_OP_JSR => 0x02000000
DDS_OP_JEQ=DDS_OP_JEQ => 0x03000000
DDS_OP_VAL_1BY=DDS_OP_VAL_1BY => 0x01
DDS_OP_VAL_2BY=DDS_OP_VAL_2BY => 0x02
DDS_OP_VAL_4BY=DDS_OP_VAL_4BY => 0x03
DDS_OP_VAL_8BY=DDS_OP_VAL_8BY => 0x04
DDS_OP_VAL_STR=DDS_OP_VAL_STR => 0x05
DDS_OP_VAL_BST=DDS_OP_VAL_BST => 0x06
DDS_OP_VAL_SEQ=DDS_OP_VAL_SEQ => 0x07
DDS_OP_VAL_ARR=DDS_OP_VAL_ARR => 0x08
DDS_OP_VAL_UNI=DDS_OP_VAL_UNI => 0x09
DDS_OP_VAL_STU=DDS_OP_VAL_STU => 0x0a
DDS_OP_TYPE_1BY=DDS_OP_TYPE_1BY => (DDS_OP_VAL_1BY << 16)
DDS_OP_TYPE_2BY=DDS_OP_TYPE_2BY => (DDS_OP_VAL_2BY << 16)
DDS_OP_TYPE_4BY=DDS_OP_TYPE_4BY => (DDS_OP_VAL_4BY << 16)
DDS_OP_TYPE_8BY=DDS_OP_TYPE_8BY => (DDS_OP_VAL_8BY << 16)
DDS_OP_TYPE_STR=DDS_OP_TYPE_STR => (DDS_OP_VAL_STR << 16)
DDS_OP_TYPE_SEQ=DDS_OP_TYPE_SEQ => (DDS_OP_VAL_SEQ << 16)
DDS_OP_TYPE_ARR=DDS_OP_TYPE_ARR => (DDS_OP_VAL_ARR << 16)
DDS_OP_TYPE_UNI=DDS_OP_TYPE_UNI => (DDS_OP_VAL_UNI << 16)
DDS_OP_TYPE_STU=DDS_OP_TYPE_STU => (DDS_OP_VAL_STU << 16)
DDS_OP_TYPE_BST=DDS_OP_TYPE_BST => (DDS_OP_VAL_BST << 16)
DDS_OP_TYPE_BOO=DDS_OP_TYPE_BOO => DDS_OP_TYPE_1BY
DDS_OP_SUBTYPE_BOO=DDS_OP_SUBTYPE_BOO => DDS_OP_SUBTYPE_1BY
DDS_OP_SUBTYPE_1BY=DDS_OP_SUBTYPE_1BY => (DDS_OP_VAL_1BY << 8)
DDS_OP_SUBTYPE_2BY=DDS_OP_SUBTYPE_2BY => (DDS_OP_VAL_2BY << 8)
DDS_OP_SUBTYPE_4BY=DDS_OP_SUBTYPE_4BY => (DDS_OP_VAL_4BY << 8)
DDS_OP_SUBTYPE_8BY=DDS_OP_SUBTYPE_8BY => (DDS_OP_VAL_8BY << 8)
DDS_OP_SUBTYPE_STR=DDS_OP_SUBTYPE_STR => (DDS_OP_VAL_STR << 8)
DDS_OP_SUBTYPE_SEQ=DDS_OP_SUBTYPE_SEQ => (DDS_OP_VAL_SEQ << 8)
DDS_OP_SUBTYPE_ARR=DDS_OP_SUBTYPE_ARR => (DDS_OP_VAL_ARR << 8)
DDS_OP_SUBTYPE_UNI=DDS_OP_SUBTYPE_UNI => (DDS_OP_VAL_UNI << 8)
DDS_OP_SUBTYPE_STU=DDS_OP_SUBTYPE_STU => (DDS_OP_VAL_STU << 8)
DDS_OP_SUBTYPE_BST=DDS_OP_SUBTYPE_BST => (DDS_OP_VAL_BST << 8)
DDS_OP_FLAG_KEY=DDS_OP_FLAG_KEY => 0x01
DDS_OP_FLAG_DEF=DDS_OP_FLAG_DEF => 0x02
DDS_INCONSISTENT_TOPIC_STATUS=DDS_INCONSISTENT_TOPIC_STATUS => 1u
DDS_OFFERED_DEADLINE_MISSED_STATUS=DDS_OFFERED_DEADLINE_MISSED_STATUS => 2u
DDS_REQUESTED_DEADLINE_MISSED_STATUS=DDS_REQUESTED_DEADLINE_MISSED_STATUS => 4u
DDS_OFFERED_INCOMPATIBLE_QOS_STATUS=DDS_OFFERED_INCOMPATIBLE_QOS_STATUS => 32u
DDS_REQUESTED_INCOMPATIBLE_QOS_STATUS=DDS_REQUESTED_INCOMPATIBLE_QOS_STATUS => 64u
DDS_SAMPLE_LOST_STATUS=DDS_SAMPLE_LOST_STATUS => 128u
DDS_SAMPLE_REJECTED_STATUS=DDS_SAMPLE_REJECTED_STATUS => 256u
DDS_DATA_ON_READERS_STATUS=DDS_DATA_ON_READERS_STATUS => 512u
DDS_DATA_AVAILABLE_STATUS=DDS_DATA_AVAILABLE_STATUS => 1024u
DDS_LIVELINESS_LOST_STATUS=DDS_LIVELINESS_LOST_STATUS => 2048u
DDS_LIVELINESS_CHANGED_STATUS=DDS_LIVELINESS_CHANGED_STATUS => 4096u
DDS_PUBLICATION_MATCHED_STATUS=DDS_PUBLICATION_MATCHED_STATUS => 8192u
DDS_SUBSCRIPTION_MATCHED_STATUS=DDS_SUBSCRIPTION_MATCHED_STATUS => 16384u
