package RoundTripModule;

/**
* RoundTripModule/DataTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/roundtrip/src/main/idl/RoundTrip.idl
* mardi 26 février 2019 11 h 28 CET
*/

public final class DataTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public RoundTripModule.DataType value = null;

  public DataTypeHolder ()
  {
  }

  public DataTypeHolder (RoundTripModule.DataType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RoundTripModule.DataTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RoundTripModule.DataTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RoundTripModule.DataTypeHelper.type ();
  }

}
