language: minimal

jdk: oraclejdk8

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.2
 
script: 
  - cd src/api/java5
  - mvn clean install

branches:
  only:
    - jna-implementation