/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
/****************************************************************

  Generated by Cyclone DDS IDL to C Translator
  File name: RhcTypes.c
  Source: RhcTypes.idl
  Generated: Thu Feb 14 16:24:50 CET 2019
  Cyclone DDS: V0.1.0

*****************************************************************/
#include "RhcTypes.h"


static const dds_key_descriptor_t RhcTypes_T_keys[2] =
{
  { "k", 0 },
  { "ks", 2 }
};

static const uint32_t RhcTypes_T_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (RhcTypes_T, k),
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (RhcTypes_T, ks),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (RhcTypes_T, x),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (RhcTypes_T, y),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (RhcTypes_T, s),
  DDS_OP_RTS
};

const dds_topic_descriptor_t RhcTypes_T_desc =
{
  sizeof (RhcTypes_T),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  2u,
  "RhcTypes::T",
  RhcTypes_T_keys,
  6,
  RhcTypes_T_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"RhcTypes\"><Struct name=\"T\"><Member name=\"k\"><Long/></Member><Member name=\"ks\"><String/></Member><Member name=\"x\"><Long/></Member><Member name=\"y\"><Long/></Member><Member name=\"s\"><String/></Member></Struct></Module></MetaData>"
};
