/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
/****************************************************************

  Generated by Cyclone DDS IDL to C Translator
  File name: RhcTypes.h
  Source: RhcTypes.idl
  Generated: Thu Feb 14 16:24:50 CET 2019
  Cyclone DDS: V0.1.0

*****************************************************************/

#include "ddsc/dds_public_impl.h"

#ifndef _DDSL_RHCTYPES_H_
#define _DDSL_RHCTYPES_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct RhcTypes_T
{
  int32_t k;
  char * ks;
  int32_t x;
  int32_t y;
  char * s;
} RhcTypes_T;

extern const dds_topic_descriptor_t RhcTypes_T_desc;

#define RhcTypes_T__alloc() \
((RhcTypes_T*) dds_alloc (sizeof (RhcTypes_T)));

#define RhcTypes_T_free(d,o) \
dds_sample_free ((d), &RhcTypes_T_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_RHCTYPES_H_ */
