package org.eclipse.cyclonedds.helloworld;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
/**
 * JNA Wrapper for library <b>helloworld</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HelloworldLibrary implements Library {
	public static final String JNA_LIBRARY_NAME = "helloworld";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(HelloworldLibrary.JNA_LIBRARY_NAME);
	static {
		Native.register(HelloworldLibrary.class, HelloworldLibrary.JNA_NATIVE_LIB);
	}
}
