/*
 * Copyright(c) 2006 to 2019 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
module one {
  module two {
    module three {

      enum Shapes { CIRCLE, TRIANGLE, SQUARE };

      struct ShapeType {
        string color;
        long x;
        long y;
        long shapetype;
      };
      // key string
      #pragma keylist ShapeType color

    };

    enum TempScale { CELSIUS, FARENHEIGHT, KELVIN };

    struct TempSensorType {
      long id;
      TempScale scale;
      float temp;
      float hum;
    };
    // key long enum
    #pragma keylist TempSensorType id scale
    
    struct SpatialPressureEstimate {
      long x;
      long y;
      long z;
      float pressure;
    };
    #pragma keylist SpatialPressureEstimate x y z
    
    struct MeteoData{
      long id;
      TempSensorType temp;
      SpatialPressureEstimate pressure;
    };
    
    struct FlightPlan{
      long id;
      MeteoData meteo;      
    };
    #pragma keylist FlightPlan id meteo.id meteo.temp.id meteo.temp.scale 

  };
};
