package ThroughputModule;


/**
* ThroughputModule/DataType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/throughput/src/main/idl/ThroughputData.idl
* lundi 25 février 2019 12 h 34 CET
*/

/**
* Updated by idl2j
* from /home/ndrianja/IST/jmobile/examples/throughput/src/main/idl/ThroughputData.idl
* lundi 25 février 2019 12 h 34 CET
*/

import ThroughputModule.KeyList;

@KeyList(
    topicType = "DataType",
    keys = {}
)
public final class DataType implements org.omg.CORBA.portable.IDLEntity
{
  public long count = (long)0;
  public byte payload[] = null;

  public DataType ()
  {
  } // ctor

  public DataType (long _count, byte[] _payload)
  {
    count = _count;
    payload = _payload;
  } // ctor

} // class DataType
