package org.eclipse.cyclonedds.helloworld;


/**
* HelloWorldData/Msg.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/cyclone-dds/src/main/idl/HelloWorldData.idl
* lundi 1 avril 2019 13 h 10 CEST
*/

/**
* Updated by idl2j
* from /home/ndrianja/IST/cyclonedds/src/api/java5/cyclone-dds/src/main/idl/HelloWorldData.idl
* lundi 1 avril 2019 13 h 10 CEST
*/

import java.util.Arrays;
import java.util.List;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

@KeyList(
    topicType = "Msg",
    keys = {"userID"}
)
public class Msg extends Structure  implements org.omg.CORBA.portable.IDLEntity
{
  public int userID = (int)0;

  // User ID
  public String message = null;

  public Msg ()
  {
    super();
  } // ctor

  public Msg (int _userID, String _message)
  {
    super();
    userID = _userID;
    message = _message;
  } // ctor

  protected List<String> getFieldOrder() {
    return Arrays.asList("userID","message");
  }

  public Structure getNewStructureFrom(Pointer peer) {
    return new Msg(peer);
  }

  public int getNativeSize() {
    return size();
  }

  public Msg(Pointer peer) {
    super(peer);
  }

  public Structure.ByReference getStructureReference(){
    Msg.ByReference bref = new Msg.ByReference();
    bref.userID = userID;
    bref.message = message;
    return bref;
  }

  public static class ByReference extends Msg implements Structure.ByReference {};

  public static class ByValue extends Msg implements Structure.ByValue {};

} // class Msg
