/*
 *                             Vortex Cafe
 *
 *    This software and documentation are Copyright 2010 to 2019 ADLINK
 *    Technology Limited, its affiliated companies and licensors. All rights
 *    reserved.
 *
 *    Licensed under the ADLINK Software License Agreement Rev 2.7 2nd October
 *    2014 (the "License"); you may not use this file except in compliance with
 *    the License.
 *    You may obtain a copy of the License at:
 *                        docs/LICENSE.html
 *
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
#include "CommonStructures.idl"
#include "subDir1/subFile1.idl"
#include "subDir1/subDir2/subFile2.idl"

module com {
  module prismtech {
    module cafe {
      module demo {
        module idl {
          struct ChatMessage {
            ::com::prismtech::cafe::demo::subDir1::Name user;
            string msg;

            ::com::prismtech::cafe::demo::subDir1::subDir2::Address addr;
            ::com::prismtech::cafe::demo::CommonStructures::EventDate date;
          };
          #pragma keylist ChatMessage user
        };
      };
    };
  };
};
