/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
/****************************************************************

  Generated by Cyclone DDS IDL to C Translator
  File name: Throughput.c
  Source: Throughput.idl
  Generated: Thu Feb 14 16:24:54 CET 2019
  Cyclone DDS: V0.1.0

*****************************************************************/
#include "Throughput.h"


static const uint32_t ThroughputModule_DataType_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (ThroughputModule_DataType, count),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (ThroughputModule_DataType, payload),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ThroughputModule_DataType_desc =
{
  sizeof (ThroughputModule_DataType),
  8u,
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "ThroughputModule::DataType",
  NULL,
  3,
  ThroughputModule_DataType_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"ThroughputModule\"><Struct name=\"DataType\"><Member name=\"count\"><ULongLong/></Member><Member name=\"payload\"><Sequence><Octet/></Sequence></Member></Struct></Module></MetaData>"
};
