/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
/****************************************************************

  Generated by Cyclone DDS IDL to C Translator
  File name: Throughput.h
  Source: Throughput.idl
  Generated: Thu Feb 14 16:24:54 CET 2019
  Cyclone DDS: V0.1.0

*****************************************************************/

#include "ddsc/dds_public_impl.h"

#ifndef _DDSL_THROUGHPUT_H_
#define _DDSL_THROUGHPUT_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct ThroughputModule_DataType
{
  uint64_t count;
  dds_sequence_t payload;
} ThroughputModule_DataType;

extern const dds_topic_descriptor_t ThroughputModule_DataType_desc;

#define ThroughputModule_DataType__alloc() \
((ThroughputModule_DataType*) dds_alloc (sizeof (ThroughputModule_DataType)));

#define ThroughputModule_DataType_free(d,o) \
dds_sample_free ((d), &ThroughputModule_DataType_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_THROUGHPUT_H_ */
