package RoundTripModule;


/**
* RoundTripModule/DataTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/roundtrip/src/main/idl/RoundTrip.idl
* mardi 26 février 2019 11 h 28 CET
*/

abstract public class DataTypeHelper
{
  private static String  _id = "IDL:RoundTripModule/DataType:1.0";

  public static void insert (org.omg.CORBA.Any a, RoundTripModule.DataType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RoundTripModule.DataType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "payload",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RoundTripModule.DataTypeHelper.id (), "DataType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RoundTripModule.DataType read (org.omg.CORBA.portable.InputStream istream)
  {
    RoundTripModule.DataType value = new RoundTripModule.DataType ();
    int _len0 = istream.read_long ();
    value.payload = new byte[_len0];
    istream.read_octet_array (value.payload, 0, _len0);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RoundTripModule.DataType value)
  {
    ostream.write_long (value.payload.length);
    ostream.write_octet_array (value.payload, 0, value.payload.length);
  }

}
