package RoundTripModule;


/**
* RoundTripModule/DataType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/jmobile/examples/roundtrip/src/main/idl/RoundTrip.idl
* mardi 26 février 2019 11 h 28 CET
*/

/**
* Updated by idl2j
* from /home/ndrianja/IST/jmobile/examples/roundtrip/src/main/idl/RoundTrip.idl
* mardi 26 février 2019 11 h 28 CET
*/


@KeyList(
    topicType = "DataType",
    keys = {}
)
public final class DataType implements org.omg.CORBA.portable.IDLEntity
{
  public byte payload[] = null;

  public DataType ()
  {
  } // ctor

  public DataType (byte[] _payload)
  {
    payload = _payload;
  } // ctor

} // class DataType
