package DDS;


/**
* DDS/BuiltinTopicKey_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class BuiltinTopicKey_tHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public BuiltinTopicKey_tHolder ()
  {
  }

  public BuiltinTopicKey_tHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.BuiltinTopicKey_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.BuiltinTopicKey_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.BuiltinTopicKey_tHelper.type ();
  }

}
