package DDS;


/**
* DDS/CMDataWriterBuiltinTopicDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class CMDataWriterBuiltinTopicDataHelper
{
  private static String  _id = "IDL:DDS/CMDataWriterBuiltinTopicData:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.CMDataWriterBuiltinTopicData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.CMDataWriterBuiltinTopicData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (3, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.BuiltinTopicKey_tHelper.id (), "BuiltinTopicKey_t", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ProductDataQosPolicyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "product",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (3, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.BuiltinTopicKey_tHelper.id (), "BuiltinTopicKey_t", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "publisher_key",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.HistoryQosPolicyHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "history",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ResourceLimitsQosPolicyHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "resource_limits",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.WriterDataLifecycleQosPolicyHelper.type ();
          _members0[6] = new org.omg.CORBA.StructMember (
            "writer_data_lifecycle",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.CMDataWriterBuiltinTopicDataHelper.id (), "CMDataWriterBuiltinTopicData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.CMDataWriterBuiltinTopicData read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.CMDataWriterBuiltinTopicData value = new DDS.CMDataWriterBuiltinTopicData ();
    value.key = DDS.BuiltinTopicKey_tHelper.read (istream);
    value.product = DDS.ProductDataQosPolicyHelper.read (istream);
    value.publisher_key = DDS.BuiltinTopicKey_tHelper.read (istream);
    value.name = istream.read_string ();
    value.history = DDS.HistoryQosPolicyHelper.read (istream);
    value.resource_limits = DDS.ResourceLimitsQosPolicyHelper.read (istream);
    value.writer_data_lifecycle = DDS.WriterDataLifecycleQosPolicyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.CMDataWriterBuiltinTopicData value)
  {
    DDS.BuiltinTopicKey_tHelper.write (ostream, value.key);
    DDS.ProductDataQosPolicyHelper.write (ostream, value.product);
    DDS.BuiltinTopicKey_tHelper.write (ostream, value.publisher_key);
    ostream.write_string (value.name);
    DDS.HistoryQosPolicyHelper.write (ostream, value.history);
    DDS.ResourceLimitsQosPolicyHelper.write (ostream, value.resource_limits);
    DDS.WriterDataLifecycleQosPolicyHelper.write (ostream, value.writer_data_lifecycle);
  }

}
