package DDS;


/**
* DDS/CMDataReaderBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class CMDataReaderBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public DDS.ProductDataQosPolicy product = null;
  public int subscriber_key[] = null;
  public String name = null;
  public DDS.HistoryQosPolicy history = null;
  public DDS.ResourceLimitsQosPolicy resource_limits = null;
  public DDS.ReaderDataLifecycleQosPolicy reader_data_lifecycle = null;
  public DDS.UserKeyQosPolicy subscription_keys = null;
  public DDS.ReaderLifespanQosPolicy reader_lifespan = null;
  public DDS.ShareQosPolicy share = null;

  public CMDataReaderBuiltinTopicData ()
  {
  } // ctor

  public CMDataReaderBuiltinTopicData (int[] _key, DDS.ProductDataQosPolicy _product, int[] _subscriber_key, String _name, DDS.HistoryQosPolicy _history, DDS.ResourceLimitsQosPolicy _resource_limits, DDS.ReaderDataLifecycleQosPolicy _reader_data_lifecycle, DDS.UserKeyQosPolicy _subscription_keys, DDS.ReaderLifespanQosPolicy _reader_lifespan, DDS.ShareQosPolicy _share)
  {
    key = _key;
    product = _product;
    subscriber_key = _subscriber_key;
    name = _name;
    history = _history;
    resource_limits = _resource_limits;
    reader_data_lifecycle = _reader_data_lifecycle;
    subscription_keys = _subscription_keys;
    reader_lifespan = _reader_lifespan;
    share = _share;
  } // ctor

} // class CMDataReaderBuiltinTopicData
