package DDS;


/**
* DDS/CMDataWriterBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class CMDataWriterBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public DDS.ProductDataQosPolicy product = null;
  public int publisher_key[] = null;
  public String name = null;
  public DDS.HistoryQosPolicy history = null;
  public DDS.ResourceLimitsQosPolicy resource_limits = null;
  public DDS.WriterDataLifecycleQosPolicy writer_data_lifecycle = null;

  public CMDataWriterBuiltinTopicData ()
  {
  } // ctor

  public CMDataWriterBuiltinTopicData (int[] _key, DDS.ProductDataQosPolicy _product, int[] _publisher_key, String _name, DDS.HistoryQosPolicy _history, DDS.ResourceLimitsQosPolicy _resource_limits, DDS.WriterDataLifecycleQosPolicy _writer_data_lifecycle)
  {
    key = _key;
    product = _product;
    publisher_key = _publisher_key;
    name = _name;
    history = _history;
    resource_limits = _resource_limits;
    writer_data_lifecycle = _writer_data_lifecycle;
  } // ctor

} // class CMDataWriterBuiltinTopicData
