package DDS;


/**
* DDS/CMDataReaderBuiltinTopicDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class CMDataReaderBuiltinTopicDataHelper
{
  private static String  _id = "IDL:DDS/CMDataReaderBuiltinTopicData:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.CMDataReaderBuiltinTopicData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.CMDataReaderBuiltinTopicData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [10];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (3, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.BuiltinTopicKey_tHelper.id (), "BuiltinTopicKey_t", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ProductDataQosPolicyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "product",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (3, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.BuiltinTopicKey_tHelper.id (), "BuiltinTopicKey_t", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "subscriber_key",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.HistoryQosPolicyHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "history",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ResourceLimitsQosPolicyHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "resource_limits",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ReaderDataLifecycleQosPolicyHelper.type ();
          _members0[6] = new org.omg.CORBA.StructMember (
            "reader_data_lifecycle",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.UserKeyQosPolicyHelper.type ();
          _members0[7] = new org.omg.CORBA.StructMember (
            "subscription_keys",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ReaderLifespanQosPolicyHelper.type ();
          _members0[8] = new org.omg.CORBA.StructMember (
            "reader_lifespan",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ShareQosPolicyHelper.type ();
          _members0[9] = new org.omg.CORBA.StructMember (
            "share",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.CMDataReaderBuiltinTopicDataHelper.id (), "CMDataReaderBuiltinTopicData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.CMDataReaderBuiltinTopicData read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.CMDataReaderBuiltinTopicData value = new DDS.CMDataReaderBuiltinTopicData ();
    value.key = DDS.BuiltinTopicKey_tHelper.read (istream);
    value.product = DDS.ProductDataQosPolicyHelper.read (istream);
    value.subscriber_key = DDS.BuiltinTopicKey_tHelper.read (istream);
    value.name = istream.read_string ();
    value.history = DDS.HistoryQosPolicyHelper.read (istream);
    value.resource_limits = DDS.ResourceLimitsQosPolicyHelper.read (istream);
    value.reader_data_lifecycle = DDS.ReaderDataLifecycleQosPolicyHelper.read (istream);
    value.subscription_keys = DDS.UserKeyQosPolicyHelper.read (istream);
    value.reader_lifespan = DDS.ReaderLifespanQosPolicyHelper.read (istream);
    value.share = DDS.ShareQosPolicyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.CMDataReaderBuiltinTopicData value)
  {
    DDS.BuiltinTopicKey_tHelper.write (ostream, value.key);
    DDS.ProductDataQosPolicyHelper.write (ostream, value.product);
    DDS.BuiltinTopicKey_tHelper.write (ostream, value.subscriber_key);
    ostream.write_string (value.name);
    DDS.HistoryQosPolicyHelper.write (ostream, value.history);
    DDS.ResourceLimitsQosPolicyHelper.write (ostream, value.resource_limits);
    DDS.ReaderDataLifecycleQosPolicyHelper.write (ostream, value.reader_data_lifecycle);
    DDS.UserKeyQosPolicyHelper.write (ostream, value.subscription_keys);
    DDS.ReaderLifespanQosPolicyHelper.write (ostream, value.reader_lifespan);
    DDS.ShareQosPolicyHelper.write (ostream, value.share);
  }

}
