package DDS;


/**
* DDS/CMSubscriberBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class CMSubscriberBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public DDS.ProductDataQosPolicy product = null;
  public int participant_key[] = null;
  public String name = null;
  public DDS.EntityFactoryQosPolicy entity_factory = null;
  public DDS.ShareQosPolicy share = null;
  public DDS.PartitionQosPolicy partition = null;

  public CMSubscriberBuiltinTopicData ()
  {
  } // ctor

  public CMSubscriberBuiltinTopicData (int[] _key, DDS.ProductDataQosPolicy _product, int[] _participant_key, String _name, DDS.EntityFactoryQosPolicy _entity_factory, DDS.ShareQosPolicy _share, DDS.PartitionQosPolicy _partition)
  {
    key = _key;
    product = _product;
    participant_key = _participant_key;
    name = _name;
    entity_factory = _entity_factory;
    share = _share;
    partition = _partition;
  } // ctor

} // class CMSubscriberBuiltinTopicData
