package DDS;


/**
* DDS/DataReaderViewQosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class DataReaderViewQosHelper
{
  private static String  _id = "IDL:DDS/DataReaderViewQos:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.DataReaderViewQos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.DataReaderViewQos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DDS.ViewKeyQosPolicyHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "view_keys",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.DataReaderViewQosHelper.id (), "DataReaderViewQos", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.DataReaderViewQos read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.DataReaderViewQos value = new DDS.DataReaderViewQos ();
    value.view_keys = DDS.ViewKeyQosPolicyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.DataReaderViewQos value)
  {
    DDS.ViewKeyQosPolicyHelper.write (ostream, value.view_keys);
  }

}
