package DDS;


/**
* DDS/DataReaderViewQos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DataReaderViewQos implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.ViewKeyQosPolicy view_keys = null;

  public DataReaderViewQos ()
  {
  } // ctor

  public DataReaderViewQos (DDS.ViewKeyQosPolicy _view_keys)
  {
    view_keys = _view_keys;
  } // ctor

} // class DataReaderViewQos
