package DDS;


/**
* DDS/DestinationOrderQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DestinationOrderQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.DestinationOrderQosPolicyKind kind = null;

  public DestinationOrderQosPolicy ()
  {
  } // ctor

  public DestinationOrderQosPolicy (DDS.DestinationOrderQosPolicyKind _kind)
  {
    kind = _kind;
  } // ctor

} // class DestinationOrderQosPolicy
