package DDS;


/**
* DDS/DestinationOrderQosPolicyKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public class DestinationOrderQosPolicyKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static DDS.DestinationOrderQosPolicyKind[] __array = new DDS.DestinationOrderQosPolicyKind [__size];

  public static final int _BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS = 0;
  public static final DDS.DestinationOrderQosPolicyKind BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS = new DDS.DestinationOrderQosPolicyKind(_BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS);
  public static final int _BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS = 1;
  public static final DDS.DestinationOrderQosPolicyKind BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS = new DDS.DestinationOrderQosPolicyKind(_BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS);

  public int value ()
  {
    return __value;
  }

  public static DDS.DestinationOrderQosPolicyKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected DestinationOrderQosPolicyKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class DestinationOrderQosPolicyKind
