package DDS;


/**
* DDS/DomainParticipantFactoryQos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DomainParticipantFactoryQos implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.EntityFactoryQosPolicy entity_factory = null;

  public DomainParticipantFactoryQos ()
  {
  } // ctor

  public DomainParticipantFactoryQos (DDS.EntityFactoryQosPolicy _entity_factory)
  {
    entity_factory = _entity_factory;
  } // ctor

} // class DomainParticipantFactoryQos
