package DDS;


/**
* DDS/DomainParticipantQos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DomainParticipantQos implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.UserDataQosPolicy user_data = null;
  public DDS.EntityFactoryQosPolicy entity_factory = null;
  public DDS.SchedulingQosPolicy watchdog_scheduling = null;
  public DDS.SchedulingQosPolicy listener_scheduling = null;

  public DomainParticipantQos ()
  {
  } // ctor

  public DomainParticipantQos (DDS.UserDataQosPolicy _user_data, DDS.EntityFactoryQosPolicy _entity_factory, DDS.SchedulingQosPolicy _watchdog_scheduling, DDS.SchedulingQosPolicy _listener_scheduling)
  {
    user_data = _user_data;
    entity_factory = _entity_factory;
    watchdog_scheduling = _watchdog_scheduling;
    listener_scheduling = _listener_scheduling;
  } // ctor

} // class DomainParticipantQos
