package DDS;

/**
* DDS/DomainParticipantFactoryQosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DomainParticipantFactoryQosHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.DomainParticipantFactoryQos value = null;

  public DomainParticipantFactoryQosHolder ()
  {
  }

  public DomainParticipantFactoryQosHolder (DDS.DomainParticipantFactoryQos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.DomainParticipantFactoryQosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.DomainParticipantFactoryQosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.DomainParticipantFactoryQosHelper.type ();
  }

}
