package DDS;


/**
* DDS/Duration_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class Duration_t implements org.omg.CORBA.portable.IDLEntity
{
  public int sec = (int)0;
  public int nanosec = (int)0;

  public Duration_t ()
  {
  } // ctor

  public Duration_t (int _sec, int _nanosec)
  {
    sec = _sec;
    nanosec = _nanosec;
  } // ctor

} // class Duration_t
