package DDS;


/**
* DDS/DurabilityQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class DurabilityQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.DurabilityQosPolicyKind kind = null;

  public DurabilityQosPolicy ()
  {
  } // ctor

  public DurabilityQosPolicy (DDS.DurabilityQosPolicyKind _kind)
  {
    kind = _kind;
  } // ctor

} // class DurabilityQosPolicy
