package DDS;


/**
* DDS/EntityFactoryQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class EntityFactoryQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public boolean autoenable_created_entities = false;

  public EntityFactoryQosPolicy ()
  {
  } // ctor

  public EntityFactoryQosPolicy (boolean _autoenable_created_entities)
  {
    autoenable_created_entities = _autoenable_created_entities;
  } // ctor

} // class EntityFactoryQosPolicy
