package DDS;


/**
* DDS/HistoryQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class HistoryQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.HistoryQosPolicyKind kind = null;
  public int depth = (int)0;

  public HistoryQosPolicy ()
  {
  } // ctor

  public HistoryQosPolicy (DDS.HistoryQosPolicyKind _kind, int _depth)
  {
    kind = _kind;
    depth = _depth;
  } // ctor

} // class HistoryQosPolicy
