package DDS;


/**
* DDS/InvalidSampleVisibilityQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class InvalidSampleVisibilityQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.InvalidSampleVisibilityQosPolicyKind kind = null;

  public InvalidSampleVisibilityQosPolicy ()
  {
  } // ctor

  public InvalidSampleVisibilityQosPolicy (DDS.InvalidSampleVisibilityQosPolicyKind _kind)
  {
    kind = _kind;
  } // ctor

} // class InvalidSampleVisibilityQosPolicy
