package DDS;


/**
* DDS/INVALID_REPRESENTATION.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public interface INVALID_REPRESENTATION
{
  public static final short value = (short)(0x7FFF);
}
