package DDS;


/**
* DDS/LatencyBudgetQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class LatencyBudgetQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.Duration_t duration = null;

  public LatencyBudgetQosPolicy ()
  {
  } // ctor

  public LatencyBudgetQosPolicy (DDS.Duration_t _duration)
  {
    duration = _duration;
  } // ctor

} // class LatencyBudgetQosPolicy
