package DDS;


/**
* DDS/LivelinessQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class LivelinessQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.LivelinessQosPolicyKind kind = null;
  public DDS.Duration_t lease_duration = null;

  public LivelinessQosPolicy ()
  {
  } // ctor

  public LivelinessQosPolicy (DDS.LivelinessQosPolicyKind _kind, DDS.Duration_t _lease_duration)
  {
    kind = _kind;
    lease_duration = _lease_duration;
  } // ctor

} // class LivelinessQosPolicy
