package DDS;


/**
* DDS/OwnershipStrengthQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class OwnershipStrengthQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public int value = (int)0;

  public OwnershipStrengthQosPolicy ()
  {
  } // ctor

  public OwnershipStrengthQosPolicy (int _value)
  {
    value = _value;
  } // ctor

} // class OwnershipStrengthQosPolicy
