package DDS;


/**
* DDS/ParticipantBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ParticipantBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public DDS.UserDataQosPolicy user_data = null;

  public ParticipantBuiltinTopicData ()
  {
  } // ctor

  public ParticipantBuiltinTopicData (int[] _key, DDS.UserDataQosPolicy _user_data)
  {
    key = _key;
    user_data = _user_data;
  } // ctor

} // class ParticipantBuiltinTopicData
