package DDS;


/**
* DDS/PresentationQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class PresentationQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.PresentationQosPolicyAccessScopeKind access_scope = null;
  public boolean coherent_access = false;
  public boolean ordered_access = false;

  public PresentationQosPolicy ()
  {
  } // ctor

  public PresentationQosPolicy (DDS.PresentationQosPolicyAccessScopeKind _access_scope, boolean _coherent_access, boolean _ordered_access)
  {
    access_scope = _access_scope;
    coherent_access = _coherent_access;
    ordered_access = _ordered_access;
  } // ctor

} // class PresentationQosPolicy
