package DDS;

/**
* DDS/PresentationQosPolicyAccessScopeKindHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class PresentationQosPolicyAccessScopeKindHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.PresentationQosPolicyAccessScopeKind value = null;

  public PresentationQosPolicyAccessScopeKindHolder ()
  {
  }

  public PresentationQosPolicyAccessScopeKindHolder (DDS.PresentationQosPolicyAccessScopeKind initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.PresentationQosPolicyAccessScopeKindHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.PresentationQosPolicyAccessScopeKindHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.PresentationQosPolicyAccessScopeKindHelper.type ();
  }

}
