package DDS;


/**
* DDS/ProductDataQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ProductDataQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public String value = null;

  public ProductDataQosPolicy ()
  {
  } // ctor

  public ProductDataQosPolicy (String _value)
  {
    value = _value;
  } // ctor

} // class ProductDataQosPolicy
