package DDS;


/**
* DDS/PublicationBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class PublicationBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public int participant_key[] = null;
  public String topic_name = null;
  public String type_name = null;
  public DDS.DurabilityQosPolicy durability = null;
  public DDS.DeadlineQosPolicy deadline = null;
  public DDS.LatencyBudgetQosPolicy latency_budget = null;
  public DDS.LivelinessQosPolicy liveliness = null;
  public DDS.ReliabilityQosPolicy reliability = null;
  public DDS.LifespanQosPolicy lifespan = null;
  public DDS.DestinationOrderQosPolicy destination_order = null;
  public DDS.UserDataQosPolicy user_data = null;
  public DDS.OwnershipQosPolicy ownership = null;
  public DDS.OwnershipStrengthQosPolicy ownership_strength = null;
  public DDS.PresentationQosPolicy presentation = null;
  public DDS.PartitionQosPolicy partition = null;
  public DDS.TopicDataQosPolicy topic_data = null;
  public DDS.GroupDataQosPolicy group_data = null;

  public PublicationBuiltinTopicData ()
  {
  } // ctor

  public PublicationBuiltinTopicData (int[] _key, int[] _participant_key, String _topic_name, String _type_name, DDS.DurabilityQosPolicy _durability, DDS.DeadlineQosPolicy _deadline, DDS.LatencyBudgetQosPolicy _latency_budget, DDS.LivelinessQosPolicy _liveliness, DDS.ReliabilityQosPolicy _reliability, DDS.LifespanQosPolicy _lifespan, DDS.DestinationOrderQosPolicy _destination_order, DDS.UserDataQosPolicy _user_data, DDS.OwnershipQosPolicy _ownership, DDS.OwnershipStrengthQosPolicy _ownership_strength, DDS.PresentationQosPolicy _presentation, DDS.PartitionQosPolicy _partition, DDS.TopicDataQosPolicy _topic_data, DDS.GroupDataQosPolicy _group_data)
  {
    key = _key;
    participant_key = _participant_key;
    topic_name = _topic_name;
    type_name = _type_name;
    durability = _durability;
    deadline = _deadline;
    latency_budget = _latency_budget;
    liveliness = _liveliness;
    reliability = _reliability;
    lifespan = _lifespan;
    destination_order = _destination_order;
    user_data = _user_data;
    ownership = _ownership;
    ownership_strength = _ownership_strength;
    presentation = _presentation;
    partition = _partition;
    topic_data = _topic_data;
    group_data = _group_data;
  } // ctor

} // class PublicationBuiltinTopicData
