package DDS;

/**
* DDS/PublisherQosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class PublisherQosHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.PublisherQos value = null;

  public PublisherQosHolder ()
  {
  }

  public PublisherQosHolder (DDS.PublisherQos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.PublisherQosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.PublisherQosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.PublisherQosHelper.type ();
  }

}
