package DDS;


/**
* DDS/PublisherQos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class PublisherQos implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.PresentationQosPolicy presentation = null;
  public DDS.PartitionQosPolicy partition = null;
  public DDS.GroupDataQosPolicy group_data = null;
  public DDS.EntityFactoryQosPolicy entity_factory = null;

  public PublisherQos ()
  {
  } // ctor

  public PublisherQos (DDS.PresentationQosPolicy _presentation, DDS.PartitionQosPolicy _partition, DDS.GroupDataQosPolicy _group_data, DDS.EntityFactoryQosPolicy _entity_factory)
  {
    presentation = _presentation;
    partition = _partition;
    group_data = _group_data;
    entity_factory = _entity_factory;
  } // ctor

} // class PublisherQos
