package DDS;


/**
* DDS/ReaderLifespanQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ReaderLifespanQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public boolean use_lifespan = false;
  public DDS.Duration_t duration = null;

  public ReaderLifespanQosPolicy ()
  {
  } // ctor

  public ReaderLifespanQosPolicy (boolean _use_lifespan, DDS.Duration_t _duration)
  {
    use_lifespan = _use_lifespan;
    duration = _duration;
  } // ctor

} // class ReaderLifespanQosPolicy
