package DDS;


/**
* DDS/ReaderDataLifecycleQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ReaderDataLifecycleQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.Duration_t autopurge_nowriter_samples_delay = null;
  public DDS.Duration_t autopurge_disposed_samples_delay = null;
  public boolean autopurge_dispose_all = false;

  // in ./etc/idlpp/dds_dcps.idl. Retain ?
  public boolean enable_invalid_samples = false;

  // @deprecated Will be replaced by invalid_sample_visibility in due time
  public DDS.InvalidSampleVisibilityQosPolicy invalid_sample_visibility = null;

  public ReaderDataLifecycleQosPolicy ()
  {
  } // ctor

  public ReaderDataLifecycleQosPolicy (DDS.Duration_t _autopurge_nowriter_samples_delay, DDS.Duration_t _autopurge_disposed_samples_delay, boolean _autopurge_dispose_all, boolean _enable_invalid_samples, DDS.InvalidSampleVisibilityQosPolicy _invalid_sample_visibility)
  {
    autopurge_nowriter_samples_delay = _autopurge_nowriter_samples_delay;
    autopurge_disposed_samples_delay = _autopurge_disposed_samples_delay;
    autopurge_dispose_all = _autopurge_dispose_all;
    enable_invalid_samples = _enable_invalid_samples;
    invalid_sample_visibility = _invalid_sample_visibility;
  } // ctor

} // class ReaderDataLifecycleQosPolicy
