package DDS;


/**
* DDS/ReliabilityQosPolicyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class ReliabilityQosPolicyHelper
{
  private static String  _id = "IDL:DDS/ReliabilityQosPolicy:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.ReliabilityQosPolicy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.ReliabilityQosPolicy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DDS.ReliabilityQosPolicyKindHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "kind",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.Duration_tHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "max_blocking_time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "synchronous",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.ReliabilityQosPolicyHelper.id (), "ReliabilityQosPolicy", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.ReliabilityQosPolicy read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.ReliabilityQosPolicy value = new DDS.ReliabilityQosPolicy ();
    value.kind = DDS.ReliabilityQosPolicyKindHelper.read (istream);
    value.max_blocking_time = DDS.Duration_tHelper.read (istream);
    value.synchronous = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.ReliabilityQosPolicy value)
  {
    DDS.ReliabilityQosPolicyKindHelper.write (ostream, value.kind);
    DDS.Duration_tHelper.write (ostream, value.max_blocking_time);
    ostream.write_boolean (value.synchronous);
  }

}
