package DDS;


/**
* DDS/ReliabilityQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ReliabilityQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.ReliabilityQosPolicyKind kind = null;
  public DDS.Duration_t max_blocking_time = null;
  public boolean synchronous = false;

  public ReliabilityQosPolicy ()
  {
  } // ctor

  public ReliabilityQosPolicy (DDS.ReliabilityQosPolicyKind _kind, DDS.Duration_t _max_blocking_time, boolean _synchronous)
  {
    kind = _kind;
    max_blocking_time = _max_blocking_time;
    synchronous = _synchronous;
  } // ctor

} // class ReliabilityQosPolicy
