package DDS;


/**
* DDS/ResourceLimitsQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ResourceLimitsQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public int max_samples = (int)0;
  public int max_instances = (int)0;
  public int max_samples_per_instance = (int)0;

  public ResourceLimitsQosPolicy ()
  {
  } // ctor

  public ResourceLimitsQosPolicy (int _max_samples, int _max_instances, int _max_samples_per_instance)
  {
    max_samples = _max_samples;
    max_instances = _max_instances;
    max_samples_per_instance = _max_samples_per_instance;
  } // ctor

} // class ResourceLimitsQosPolicy
