package DDS;


/**
* DDS/SchedulingClassQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class SchedulingClassQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.SchedulingClassQosPolicyKind kind = null;

  public SchedulingClassQosPolicy ()
  {
  } // ctor

  public SchedulingClassQosPolicy (DDS.SchedulingClassQosPolicyKind _kind)
  {
    kind = _kind;
  } // ctor

} // class SchedulingClassQosPolicy
