package DDS;


/**
* DDS/SchedulingQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class SchedulingQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.SchedulingClassQosPolicy scheduling_class = null;
  public DDS.SchedulingPriorityQosPolicy scheduling_priority_kind = null;
  public int scheduling_priority = (int)0;

  public SchedulingQosPolicy ()
  {
  } // ctor

  public SchedulingQosPolicy (DDS.SchedulingClassQosPolicy _scheduling_class, DDS.SchedulingPriorityQosPolicy _scheduling_priority_kind, int _scheduling_priority)
  {
    scheduling_class = _scheduling_class;
    scheduling_priority_kind = _scheduling_priority_kind;
    scheduling_priority = _scheduling_priority;
  } // ctor

} // class SchedulingQosPolicy
