package DDS;


/**
* DDS/SchedulingPriorityQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class SchedulingPriorityQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.SchedulingPriorityQosPolicyKind kind = null;

  public SchedulingPriorityQosPolicy ()
  {
  } // ctor

  public SchedulingPriorityQosPolicy (DDS.SchedulingPriorityQosPolicyKind _kind)
  {
    kind = _kind;
  } // ctor

} // class SchedulingPriorityQosPolicy
