package DDS;


/**
* DDS/ShareQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ShareQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean enable = false;

  public ShareQosPolicy ()
  {
  } // ctor

  public ShareQosPolicy (String _name, boolean _enable)
  {
    name = _name;
    enable = _enable;
  } // ctor

} // class ShareQosPolicy
