package DDS;


/**
* DDS/TimeBasedFilterQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class TimeBasedFilterQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.Duration_t minimum_separation = null;

  public TimeBasedFilterQosPolicy ()
  {
  } // ctor

  public TimeBasedFilterQosPolicy (DDS.Duration_t _minimum_separation)
  {
    minimum_separation = _minimum_separation;
  } // ctor

} // class TimeBasedFilterQosPolicy
