package DDS;

/**
* DDS/Time_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class Time_tHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.Time_t value = null;

  public Time_tHolder ()
  {
  }

  public Time_tHolder (DDS.Time_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.Time_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.Time_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.Time_tHelper.type ();
  }

}
