package DDS;

/**
* DDS/TopicQosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class TopicQosHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.TopicQos value = null;

  public TopicQosHolder ()
  {
  }

  public TopicQosHolder (DDS.TopicQos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.TopicQosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.TopicQosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.TopicQosHelper.type ();
  }

}
