package DDS;


/**
* DDS/TopicBuiltinTopicDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class TopicBuiltinTopicDataHelper
{
  private static String  _id = "IDL:DDS/TopicBuiltinTopicData:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.TopicBuiltinTopicData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.TopicBuiltinTopicData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [16];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (3, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.BuiltinTopicKey_tHelper.id (), "BuiltinTopicKey_t", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "type_name",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.DurabilityQosPolicyHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "durability",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.DurabilityServiceQosPolicyHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "durability_service",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.DeadlineQosPolicyHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "deadline",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.LatencyBudgetQosPolicyHelper.type ();
          _members0[6] = new org.omg.CORBA.StructMember (
            "latency_budget",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.LivelinessQosPolicyHelper.type ();
          _members0[7] = new org.omg.CORBA.StructMember (
            "liveliness",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ReliabilityQosPolicyHelper.type ();
          _members0[8] = new org.omg.CORBA.StructMember (
            "reliability",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.TransportPriorityQosPolicyHelper.type ();
          _members0[9] = new org.omg.CORBA.StructMember (
            "transport_priority",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.LifespanQosPolicyHelper.type ();
          _members0[10] = new org.omg.CORBA.StructMember (
            "lifespan",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.DestinationOrderQosPolicyHelper.type ();
          _members0[11] = new org.omg.CORBA.StructMember (
            "destination_order",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.HistoryQosPolicyHelper.type ();
          _members0[12] = new org.omg.CORBA.StructMember (
            "history",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.ResourceLimitsQosPolicyHelper.type ();
          _members0[13] = new org.omg.CORBA.StructMember (
            "resource_limits",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.OwnershipQosPolicyHelper.type ();
          _members0[14] = new org.omg.CORBA.StructMember (
            "ownership",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.TopicDataQosPolicyHelper.type ();
          _members0[15] = new org.omg.CORBA.StructMember (
            "topic_data",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.TopicBuiltinTopicDataHelper.id (), "TopicBuiltinTopicData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.TopicBuiltinTopicData read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.TopicBuiltinTopicData value = new DDS.TopicBuiltinTopicData ();
    value.key = DDS.BuiltinTopicKey_tHelper.read (istream);
    value.name = istream.read_string ();
    value.type_name = istream.read_string ();
    value.durability = DDS.DurabilityQosPolicyHelper.read (istream);
    value.durability_service = DDS.DurabilityServiceQosPolicyHelper.read (istream);
    value.deadline = DDS.DeadlineQosPolicyHelper.read (istream);
    value.latency_budget = DDS.LatencyBudgetQosPolicyHelper.read (istream);
    value.liveliness = DDS.LivelinessQosPolicyHelper.read (istream);
    value.reliability = DDS.ReliabilityQosPolicyHelper.read (istream);
    value.transport_priority = DDS.TransportPriorityQosPolicyHelper.read (istream);
    value.lifespan = DDS.LifespanQosPolicyHelper.read (istream);
    value.destination_order = DDS.DestinationOrderQosPolicyHelper.read (istream);
    value.history = DDS.HistoryQosPolicyHelper.read (istream);
    value.resource_limits = DDS.ResourceLimitsQosPolicyHelper.read (istream);
    value.ownership = DDS.OwnershipQosPolicyHelper.read (istream);
    value.topic_data = DDS.TopicDataQosPolicyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.TopicBuiltinTopicData value)
  {
    DDS.BuiltinTopicKey_tHelper.write (ostream, value.key);
    ostream.write_string (value.name);
    ostream.write_string (value.type_name);
    DDS.DurabilityQosPolicyHelper.write (ostream, value.durability);
    DDS.DurabilityServiceQosPolicyHelper.write (ostream, value.durability_service);
    DDS.DeadlineQosPolicyHelper.write (ostream, value.deadline);
    DDS.LatencyBudgetQosPolicyHelper.write (ostream, value.latency_budget);
    DDS.LivelinessQosPolicyHelper.write (ostream, value.liveliness);
    DDS.ReliabilityQosPolicyHelper.write (ostream, value.reliability);
    DDS.TransportPriorityQosPolicyHelper.write (ostream, value.transport_priority);
    DDS.LifespanQosPolicyHelper.write (ostream, value.lifespan);
    DDS.DestinationOrderQosPolicyHelper.write (ostream, value.destination_order);
    DDS.HistoryQosPolicyHelper.write (ostream, value.history);
    DDS.ResourceLimitsQosPolicyHelper.write (ostream, value.resource_limits);
    DDS.OwnershipQosPolicyHelper.write (ostream, value.ownership);
    DDS.TopicDataQosPolicyHelper.write (ostream, value.topic_data);
  }

}
