package DDS;


/**
* DDS/TopicBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class TopicBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public int key[] = null;
  public String name = null;
  public String type_name = null;
  public DDS.DurabilityQosPolicy durability = null;
  public DDS.DurabilityServiceQosPolicy durability_service = null;
  public DDS.DeadlineQosPolicy deadline = null;
  public DDS.LatencyBudgetQosPolicy latency_budget = null;
  public DDS.LivelinessQosPolicy liveliness = null;
  public DDS.ReliabilityQosPolicy reliability = null;
  public DDS.TransportPriorityQosPolicy transport_priority = null;
  public DDS.LifespanQosPolicy lifespan = null;
  public DDS.DestinationOrderQosPolicy destination_order = null;
  public DDS.HistoryQosPolicy history = null;
  public DDS.ResourceLimitsQosPolicy resource_limits = null;
  public DDS.OwnershipQosPolicy ownership = null;
  public DDS.TopicDataQosPolicy topic_data = null;

  public TopicBuiltinTopicData ()
  {
  } // ctor

  public TopicBuiltinTopicData (int[] _key, String _name, String _type_name, DDS.DurabilityQosPolicy _durability, DDS.DurabilityServiceQosPolicy _durability_service, DDS.DeadlineQosPolicy _deadline, DDS.LatencyBudgetQosPolicy _latency_budget, DDS.LivelinessQosPolicy _liveliness, DDS.ReliabilityQosPolicy _reliability, DDS.TransportPriorityQosPolicy _transport_priority, DDS.LifespanQosPolicy _lifespan, DDS.DestinationOrderQosPolicy _destination_order, DDS.HistoryQosPolicy _history, DDS.ResourceLimitsQosPolicy _resource_limits, DDS.OwnershipQosPolicy _ownership, DDS.TopicDataQosPolicy _topic_data)
  {
    key = _key;
    name = _name;
    type_name = _type_name;
    durability = _durability;
    durability_service = _durability_service;
    deadline = _deadline;
    latency_budget = _latency_budget;
    liveliness = _liveliness;
    reliability = _reliability;
    transport_priority = _transport_priority;
    lifespan = _lifespan;
    destination_order = _destination_order;
    history = _history;
    resource_limits = _resource_limits;
    ownership = _ownership;
    topic_data = _topic_data;
  } // ctor

} // class TopicBuiltinTopicData
