package DDS;


/**
* DDS/TypeBuiltinTopicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class TypeBuiltinTopicData implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public short data_representation_id = (short)0;
  public DDS.TypeHash type_hash = null;
  public byte meta_data[] = null;
  public byte extentions[] = null;

  public TypeBuiltinTopicData ()
  {
  } // ctor

  public TypeBuiltinTopicData (String _name, short _data_representation_id, DDS.TypeHash _type_hash, byte[] _meta_data, byte[] _extentions)
  {
    name = _name;
    data_representation_id = _data_representation_id;
    type_hash = _type_hash;
    meta_data = _meta_data;
    extentions = _extentions;
  } // ctor

} // class TypeBuiltinTopicData
