package DDS;


/**
* DDS/TypeHash.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class TypeHash implements org.omg.CORBA.portable.IDLEntity
{
  public long msb = (long)0;
  public long lsb = (long)0;

  public TypeHash ()
  {
  } // ctor

  public TypeHash (long _msb, long _lsb)
  {
    msb = _msb;
    lsb = _lsb;
  } // ctor

} // class TypeHash
