package DDS;


/**
* DDS/TypeBuiltinTopicDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

abstract public class TypeBuiltinTopicDataHelper
{
  private static String  _id = "IDL:DDS/TypeBuiltinTopicData:1.0";

  public static void insert (org.omg.CORBA.Any a, DDS.TypeBuiltinTopicData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DDS.TypeBuiltinTopicData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.DataRepresentationId_tHelper.id (), "DataRepresentationId_t", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "data_representation_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = DDS.TypeHashHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "type_hash",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.octSeqHelper.id (), "octSeq", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "meta_data",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DDS.octSeqHelper.id (), "octSeq", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "extentions",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DDS.TypeBuiltinTopicDataHelper.id (), "TypeBuiltinTopicData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DDS.TypeBuiltinTopicData read (org.omg.CORBA.portable.InputStream istream)
  {
    DDS.TypeBuiltinTopicData value = new DDS.TypeBuiltinTopicData ();
    value.name = istream.read_string ();
    value.data_representation_id = istream.read_short ();
    value.type_hash = DDS.TypeHashHelper.read (istream);
    value.meta_data = DDS.octSeqHelper.read (istream);
    value.extentions = DDS.octSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DDS.TypeBuiltinTopicData value)
  {
    ostream.write_string (value.name);
    ostream.write_short (value.data_representation_id);
    DDS.TypeHashHelper.write (ostream, value.type_hash);
    DDS.octSeqHelper.write (ostream, value.meta_data);
    DDS.octSeqHelper.write (ostream, value.extentions);
  }

}
