package DDS;


/**
* DDS/UserKeyQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class UserKeyQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public boolean enable = false;
  public String expression = null;

  public UserKeyQosPolicy ()
  {
  } // ctor

  public UserKeyQosPolicy (boolean _enable, String _expression)
  {
    enable = _enable;
    expression = _expression;
  } // ctor

} // class UserKeyQosPolicy
