package DDS;

/**
* DDS/ViewKeyQosPolicyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ViewKeyQosPolicyHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.ViewKeyQosPolicy value = null;

  public ViewKeyQosPolicyHolder ()
  {
  }

  public ViewKeyQosPolicyHolder (DDS.ViewKeyQosPolicy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.ViewKeyQosPolicyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.ViewKeyQosPolicyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.ViewKeyQosPolicyHelper.type ();
  }

}
