package DDS;


/**
* DDS/ViewKeyQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_dcps_builtintopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class ViewKeyQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public boolean use_key_list = false;
  public String key_list[] = null;

  public ViewKeyQosPolicy ()
  {
  } // ctor

  public ViewKeyQosPolicy (boolean _use_key_list, String[] _key_list)
  {
    use_key_list = _use_key_list;
    key_list = _key_list;
  } // ctor

} // class ViewKeyQosPolicy
