package DDS;

/**
* DDS/WriterDataLifecycleQosPolicyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class WriterDataLifecycleQosPolicyHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.WriterDataLifecycleQosPolicy value = null;

  public WriterDataLifecycleQosPolicyHolder ()
  {
  }

  public WriterDataLifecycleQosPolicyHolder (DDS.WriterDataLifecycleQosPolicy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.WriterDataLifecycleQosPolicyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.WriterDataLifecycleQosPolicyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.WriterDataLifecycleQosPolicyHelper.type ();
  }

}
