package DDS;


/**
* DDS/WriterDataLifecycleQosPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ndrianja/IST/cyclonedds/src/api/java5/omg-dds/src/main/idl/dds_builtinTopics.idl
* jeudi 28 février 2019 10 h 26 CET
*/

public final class WriterDataLifecycleQosPolicy implements org.omg.CORBA.portable.IDLEntity
{
  public boolean autodispose_unregistered_instances = false;
  public DDS.Duration_t autopurge_suspended_samples_delay = null;
  public DDS.Duration_t autounregister_instance_delay = null;

  public WriterDataLifecycleQosPolicy ()
  {
  } // ctor

  public WriterDataLifecycleQosPolicy (boolean _autodispose_unregistered_instances, DDS.Duration_t _autopurge_suspended_samples_delay, DDS.Duration_t _autounregister_instance_delay)
  {
    autodispose_unregistered_instances = _autodispose_unregistered_instances;
    autopurge_suspended_samples_delay = _autopurge_suspended_samples_delay;
    autounregister_instance_delay = _autounregister_instance_delay;
  } // ctor

} // class WriterDataLifecycleQosPolicy
